### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by prisae** [Statoil/pylops#1]
I suggest to change the module name from `lops` to `pylops`, to be the same as the package name to install.

I installed it with `pip install pylops`, fired-up an IPython session, and run `import pylops` just to get an error that `pylops` is apparently not installed. So you have to go to the documentation and examples to find out how to call it. Ah, it's name is `lops`, so `import lops`.

I might not be the only one facing that issue. Most modules follow the convention to name the module the same as the package you install (e.g. `numpy`, `scipy`, `numba`, `matplotlib`, basically most I can think of, although there are exceptions).

I thought I open an issue to discuss it and change it now (`v1.0.1`) or never, as the package is still pretty new and not too much code is written yet with `import lops`. This will probably change pretty soon and changing the module name would not be a good idea anymore down the road.

**Comment by mrava87** [comment]
Agree. I thought it would make sense to just have ``lops`` when you are already in the python world, but I can see this would generate more confusion than anything else.

I have changed the module so that from version 1.0.1 you can do ``import lops``. I know this is not compatible with version 1.0.0 but since I don't expect many people to have started using PyLops yet I didn't think it would be needed to boost the version to 2.0.0.

Also in the README ``Getting started`` section I have now added a line to show how to import pylons. 

**NOTE**: having some issues to put v1.0.1 on PyPi

```
HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```
seems like I did it before while I was testing stuff and had by mistake boost up my version and PyPI doesn't seem to allow uploading versions that have been previously removed. Unless you have a suggestion here I suggest to wait until we have v1.1.0 (going to add some new operators soon anyways) and then upload that to PyPI.

**Comment by prisae** [comment]
Waiting for `v1.1.0` is fine. Or simply bump it to version `v1.0.2` now without any further changes.

**Comment by prisae** [comment]
> I have changed the module so that from version 1.0.1 you can do import lops.

I assume you wanted to say

> I have changed the module so that from version 1.0.1 you can do import pylops.

**Comment by mrava87** [comment]
Aaah yep, I fixed it :) otherwise that would be much of a change ;)

**Comment by prisae** [comment]
Indeed :smile: Closing it then, thanks!
